### ISSUE TITLE
Updates with side-loaded information

### ISSUE THREAD

**Issue by blester125** [r-three/git-theta#154]

**Comment by craffel** [comment]
E.g. factors in low-rank updates, indices/values in sparse updates... should be generic.

**Comment by blester125** [comment]
Breakdown of the cases/results for update types we talked about on Friday.

## Input Cases:
1. The original model parameters and PEM-parameters are saved in the model checkpoint together.
2. The PEM-parameters have been "applied" to the original model parameters, yields the same model tree as the original model
3. The PEM-parameters are saved disjointly from the original model parameters, probably in some model tree that have a similar shape to the original parameters

## Output Cases:
a. The smudged checkpoint has the original parameters and the PEM-parameters in a unified model tree
b. The smudged checkpoint has the PEM-parameters "applied" to the model weights.

# Implementations and Pros/Cons

* 1 $\rightarrow$ a: This is already supported using dense updates. This is efficient in git-theta because we snapshot the parameters so only changed things (the PEM-parameters) are changed. This is inefficient in training code as the whole model is serialized each step (even the unchanging base parameters) so save during training can be slow.
* 2 $\rightarrow$ b: This is mostly supported using special update types. The "applied" updates are back-filled based on the different between the current parameter and the previous parameter value. This results in efficient storage in git-theta, but can lead to some numerical weirdness and requires computation on git-theta. It also requires the end user to fold the PEM update into the original parameter. This could also be extended to 2 $\rightarrow$ a by changing how we write things 
* 3 $\rightarrow$ a: This can be implemented pretty easy. Update classes can basically be removed as method as we just need to do a union on the model trees. There may also be edge cases around needing to accept 2 checkpoints (one with the original parameters to verify that they aren't using a modified checkpoint and one with the PEM-parameters).

From the "collaborative model building" aspect, the setup produces a model + PEM-parameters to do task A, it doesn't produce a model to do task A. So users have to have code that combines the model + PEM-parameters themselves. In a case where someone is distributing just model checkpoints, a user could checkout the newest version and (if they don't have the combine parameter code) essentially use a checkpoint from a previous commit instead of the new one.

If the user is already only writing the small parameter efficient parameters it can also reduce some of the gains git-theta brings wrt storage.

* 3 $\rightarrow$ b: This can be implemented pretty easy, Update classes need to be update to know the mapping between parameter names and PEM names (i.e. it knows to grab `.../param_name/lora_A` and `.../param_name/lora_B` to update `.../param_name`) and the apply update method uses these values to calculate the new parameter value. This can have issues where the application of the PEM parameters can have hyper parameters that you can't tune once the model is committed.

So we should decide exactly what we want to support. Another question is how to people normally write out their parameters? In t5x you always have at least one full parameter write for preemption recovery and it is a lot easier to just dump out the whole model so I feel like a lot of people just do option 1, but t-few does option 3 so we want to be able to support that efficiently while still having a large value add from git-theta.

**Comment by craffel** [comment]
## Sketch of implementation

Consider 3 possible efficient updates: sparse, low-rank, or quantization.

1. If a user wants to perform a dense update (entirely new set of values for a given parameter group), they can just run `git add model.pt` as normal.
2. If a user wants to perform an efficient update, they need to run `git theta add model.pt --update-type=sparse --update-data=update.pt`.
  a. [Here](https://github.com/r-three/git-theta/blob/main/bin/git-theta#L58) is the list of allowable updates to provide here; this should be auto-populated based on the registered plugins
  b. We assume that the `--update-data` argument uses the same checkpoint format as model.pt; we could consider adding another argument to allow for a different format later.
4. git-theta will look for the side-loaded information in update.pt based on registered data keys in the corresponding `IncrementalUpdate` class (we need to change the IncrementalUpdate classes so that they specifically register data keys as class attributes or something). We assume that they have the naming convention `.../param_name/data_key_name` where `data_key_name` is one of the registered data keys in the IncrementalUpdate class. For now, we also assume that all of the metadata/hyperparameters/data (e.g. low-rank factors, quantization level) needed to specify the update can be provided in this way. If git-theta encounters `.../param_name/data_key_name` where `data_key_name` is not a valid key for the specified update type for some parameter group, it will throw an informative error.
5. The updated `model.pt` file should be written back to disk.

If we want to support a case where different update types are used for different parameter groups, the user would just save out different update.pt files and run `git theta add` multiple times.

As part of doing this, we'll remove the `calculate_update` functions from the `IncrementalUpdate` classes.

**Comment by blester125** [comment]
> As part of doing this, we'll remove the calculate_update functions from the IncrementalUpdate classes.

I think the IncrementalUpdate class could support both the inferred version and the sideloaded version if we dispatch between 2 functions based on if update-data was supplied or not. Or we can remove parameter inference (and probably the LSH?)

**Comment by craffel** [comment]
When we discussed this a few weeks back, the consensus was that `calculate_update` would usually involve weird/hacky stuff that we don't want to encourage, like:
1) Having to pick a threshold for what zero is when building a sparse update
2) Having to pick a singular value threshold for determining the rank of an update
3) Having to decide what to round when doing an IA3-style update
4) Having to try to guess the quantization level for quantization updates
etc. I'm not sure what you mean by "remove parameter inference". I think we still need the LSH because of the nondeterminism of applying updates.

**Comment by blester125** [comment]
I've been working on this, one issue I have been having is that `model.pt` is unchanged. This means that 1) our checks for if a parameter is unchanged are always true so the update code is never actually run. 2) git often doesn't actually call our filter unless your run `touch model.pt` as the timestamp is older than the last commit (actually it seems like it caches timestamps so running things like add multiple times result in no-ops later).

I have a decent solution to the first issue, not sure what to do about the second.

**Comment by craffel** [comment]
Wouldn't we be adding a side-loaded update via git theta add, in which case we don't need git to be aware that an update has taken place? It's not a great UI but maybe that's the best we can do?

**Comment by blester125** [comment]
Good point, I'll look into changing the mtime in git theta add so the inner call to git add works.

**Comment by blester125** [comment]
https://github.com/r-three/git-theta/pull/201 has a version of this up and running for sparse updates.

**Comment by blester125** [comment]
We currently have support for sparse, lowrank, and ia3 updates
