### ISSUE TITLE
Update README and examples

### ISSUE THREAD

**Issue by craffel** [r-three/git-theta#47]

**Comment by muqeeth** [comment]
# How to use this repository?
## LFS installation 
Download the LFS package from the [website](https://github.com/git-lfs/git-lfs/releases/tag/v3.2.0). For Linux users, download the amd64 version from the list of assests in the website. 

## Getting started
clone the repository  
```bash
git clone https://github.com/r-three/git-cml.git
```
Install the packages by running:
```bash
pip install -e .
```
The following lines will be added to the `.gitconfig` file in the home directory after the successful installation. 
```
[filter "lfs"]
        smudge = git-lfs smudge -- %f
        required = true
        clean = git-lfs clean -- %f
[filter "cml"]
        clean = git-cml-filter clean %f
        smudge = git-cml-filter smudge %f
        required = true
```

## Installing git cml
You can initialize the git cml in the root directory of our repository which consists of code and models as follows:
```bash
git cml install
```
# Example Usage
The text files in the repository are tracked using the git. However, the model checkpoint needs to be tracked using git cml. In order to do that, run this command
```bash 
git cml track <path-to-model>
```

The above command adds the following lines to the `.gitattributes` files in the root directory of the repository.
```
".git_cml/<model-name>/**/params/[0-9]*" filter=lfs diff=lfs merge=lfs -text
<path-to-model> filter=cml
```
After this, add the model to the git by running the command 
```bash
git cml add <path-to-model>
```
After running all above commands, `.git_cml` folder is created in the root directory of the repository. 
This .git_cml folder stores the parameters of the model in tensorstore format. For example, consider a key `decoder.block.0.layer.0.SelfAttention.k.weight` in the model checkpoint with name `pytorch_model.bin`, the corresponding parameters of the key are stored as the following hierarchy `.git_cml/pytorch_model.bin/decoder.block.0.layer.0.SelfAttention.k.weight` inside `.git_cml` folder. 

After adding the checkpoint and other files that are modified, you can commit the changes and push to the remote. 
The remote has `.git_cml/<model-name>` folder in it where instead of the actual params, git remote shows the params are stored as LFS objects.

**Comment by craffel** [comment]
Make a pull request please (after updating the name).

**Comment by craffel** [comment]
## Outline

- Brief overview of what git-theta is
	- How and why it's different from treating the checkpoint as a blob of data and what it supports with lots of links
- Somewhat comprehensive usage example
	- Use the example from the paper
- Specific usage examples
	- Parameter-efficient updates
		- Enumerate the different ways that we support this
	- Performing a merge
	- Trying out a different version of a model on a branch
- Extending git-theta
	- Adding update types (talk to Muqeeth)
	- Adding merge methods
	- Adding checkpoint formats
- Why do I need git-theta (how the internals work)
	- Why not git-lfs
	- How we handle parameter-efficient updates
	- How we handle merging
	- How we do hashing

**Comment by nkandpa2** [comment]
Here's a google doc to iterate on the README
https://docs.google.com/document/d/1LxCqdZxh1HXvOOzYBnKPR5WXz7NbxdHk1eCYh1ovm5w/edit?usp=sharing
