### ISSUE TITLE
use tensorstore async for writing out parameter group files

### ISSUE THREAD

**Issue by craffel** [r-three/git-theta#61]

**Comment by blester125** [comment]
Mixing async and normal code can be tricky. Here is the skeleton of a common way to do it (sorry if I over-explain).

1) Update the calls to tenorstore code to use the async versions of things (generally add an await and turn the function into an async def)
2) Make a write all function who's job is to start all of the async tasks
3) Execute this writer in a blocking way.

```python
async write_tracked_file(...):
  """This is the update to make the tensorstore write async."""
  
 async write_all_tracked_files(...):
  """This is what schedules the async tasks to be done concurrently."""
   await aysncio.gather(
       write_tracked_file(x) for x in ...
  )

# From your real code. This is executing it in a blocking way in the main synchronous code
asyncio.run(write_all_tacked_files(...))
```

If want to have a minimum python version of 3.7 we can just use this run, otherwise we probably need a custom runner like

```python
def async_run(to_run):
  loop = asyncio.get_event_loop()
  return loop.run_until_complete(write_all_tracked_files)
```

Let me know if anything is unclear

**Comment by blester125** [comment]
The new update class modules changes how this will need to be implemented, we probably need to have `async` versions of the write and apply methods on those objects. We will also need to see if multiple async methods accessing different git commits causes contention, but effective parallelism/concurrency could be a major win

**Comment by blester125** [comment]
This was done in #121
